In [2]:
!pip install numpy
!pip install pandas
!pip install matplotlib

Requirement already satisfied: numpy in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.26.2)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (4.46.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.26.2)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
excel_file_path = 'Anger_Train.xlsx'

In [6]:
df = pd.read_excel(excel_file_path)

In [7]:
df

                                       Combined_Column
0    10000   How the fu*k! Who the heck! moved my f...
1    10001   So my Indian Uber driver just called s...
2    10002   @DPD_UK I asked for my parcel to be de...
3    10003   so ef whichever butt wipe pulled the f...
4    10004   Don't join @BTCare they put the phone ...
..                                                 ...
936  10936   @Jen_ny69 People will always get offen...
937  10937   @gayla_weeks1 I try not to let my ange...
938  10938   I hope my hustle don't offend nobody  ...
939  10939   Just watched Django Unchained, Other p...
940  10940   Lol little things like that make me so...

[941 rows x 1 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Combined_Column  941 non-null    object
dtypes: object(1)
memory usage: 7.5+ KB

In [9]:
# Splitting the combined column into separate columns
df[['Index', 'Comment', 'Emotion', 'Correlation']] = df['Combined_Column'].str.extract(r'^(\d+)\s+(.*?)\s+(\w+)\s+([\d.]+|None)$')

# Dropping the original combined column
df.drop(columns=['Combined_Column'], inplace=True)

In [10]:
df

,Index,Comment,Emotion,Correlation
0,10000,How the fu*k! Who the heck! moved my fridge!.....,anger,0.938
1,10001,So my Indian Uber driver just called someone t...,anger,0.896
2,10002,@DPD_UK I asked for my parcel to be delivered ...,anger,0.896
3,10003,so ef whichever butt wipe pulled the fire alar...,anger,0.896
4,10004,Don't join @BTCare they put the phone down on ...,anger,0.896
...,...,...,...,...
936,NaN,NaN,NaN,NaN
937,NaN,NaN,NaN,NaN
938,NaN,NaN,NaN,NaN
939,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,NaN

In [11]:
df = df.dropna()

In [12]:
df

,Index,Comment,Emotion,Correlation
0,10000,How the fu*k! Who the heck! moved my fridge!.....,anger,0.938
1,10001,So my Indian Uber driver just called someone t...,anger,0.896
2,10002,@DPD_UK I asked for my parcel to be delivered ...,anger,0.896
3,10003,so ef whichever butt wipe pulled the fire alar...,anger,0.896
4,10004,Don't join @BTCare they put the phone down on ...,anger,0.896
...,...,...,...,...
852,10852,rose incense are the best thing I've ever bought,anger,0.125
853,10853,@jaaames1993 Literally burst out laughing.,anger,0.067
854,10854,Follow up. Follow through. Be . #success,anger,0.125
855,10855,Wrinkles should merely hide where frown have b...,anger,0.125
856,10856,Love the new song I can't stop thinking about ...,anger,0.083

In [13]:
pip install nltk

Requirement already satisfied: nltk in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.8.1)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: click in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (4.66.1)
Requirement already satisfied: colorama in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from click->nltk) (0.4.6)

In [14]:
import pandas as pd
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

# Download NLTK resources
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [15]:
# Load the sentiment intensity analyzer
sia = SentimentIntensityAnalyzer()

# Function to measure anger intensity in comments
def measure_anger_intensity(comment):
    scores = sia.polarity_scores(comment)
    return scores['neg']

# Apply the function to the DataFrame
df['anger_intensity'] = df['Comment'].apply(measure_anger_intensity)

C:\Users\DELL\AppData\Local\Temp\ipykernel_15316\1066420457.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['anger_intensity'] = df['Comment'].apply(measure_anger_intensity)

In [16]:
df

,Index,Comment,Emotion,Correlation,anger_intensity
0,10000,How the fu*k! Who the heck! moved my fridge!.....,anger,0.938,0.000
1,10001,So my Indian Uber driver just called someone t...,anger,0.896,0.000
2,10002,@DPD_UK I asked for my parcel to be delivered ...,anger,0.896,0.000
3,10003,so ef whichever butt wipe pulled the fire alar...,anger,0.896,0.186
4,10004,Don't join @BTCare they put the phone down on ...,anger,0.896,0.191
...,...,...,...,...,...
852,10852,rose incense are the best thing I've ever bought,anger,0.125,0.000
853,10853,@jaaames1993 Literally burst out laughing.,anger,0.067,0.000
854,10854,Follow up. Follow through. Be . #success,anger,0.125,0.000
855,10855,Wrinkles should merely hide where frown have b...,anger,0.125,0.159
856,10856,Love the new song I can't stop thinking about ...,anger,0.083,0.000

In [17]:
file_path = 'anger_intensity.xlsx'

# Save the DataFrame as an Excel file
df.to_excel(file_path, index=False)

In [18]:
excel_file_path = 'Anger_Test.xlsx'

In [19]:
df2 = pd.read_excel(excel_file_path)

In [20]:
df2

                                       Combined_Column
0    10941   At the point today where if someone sa...
1    10942   @CorningFootball  IT'S GAME DAY!!!!   ...
2    10943   This game has pissed me off more than ...
3    10944   @spamvicious I've just found out it's ...
4    10945   @moocowward @mrsajhargreaves @Melly77 ...
..                                                 ...
755  11696   @ggreenwald What if the supposed animo...
756  11697   Will BYU's offense score 24+ vs WVU?  ...
757  11698   Id love 2 c Gyimah in action but his c...
758  11699   Forgiving means operating with God's s...
759  11700   i've got a lot of tokens saved up and ...

[760 rows x 1 columns]

In [21]:
pattern = r'(\d+)\s+(.+?)\s+(\w+)\s+(NONE)'

# Apply the pattern using str.extract method to extract values into separate columns
df3 = df2['Combined_Column'].str.extract(pattern, expand=True)

# Rename columns
df3.columns = ['Index', 'Comment', 'Emotion', 'Correlation']

In [22]:
df3

,Index,Comment,Emotion,Correlation
0,10941,At the point today where if someone says somet...,anger,NONE
1,10942,@CorningFootball IT'S GAME DAY!!!! T MIN...,anger,NONE
2,10943,This game has pissed me off more than any othe...,anger,NONE
3,10944,@spamvicious I've just found out it's Candice ...,anger,NONE
4,10945,@moocowward @mrsajhargreaves @Melly77 @GaryBar...,anger,NONE
...,...,...,...,...
755,11696,@ggreenwald What if the supposed animosity is ...,anger,NONE
756,11697,Will BYU's offense score 24+ vs WVU?,anger,NONE
757,11698,Id love 2 c Gyimah in action but his coach is ...,anger,NONE
758,11699,Forgiving means operating with God's spirit &a...,anger,NONE
759,11700,i've got a lot of tokens saved up and i wanna ...,anger,NONE

In [23]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import mean_squared_error

# Load training and test data
train_data = df
test_data = df3

# Define X_train and y_train
X_train = train_data['Comment']
y_train = train_data['Correlation']

# Define X_test
X_test = test_data['Comment']

# Vectorize comments using TF-IDF
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train Random Forest Regressor model
model = RandomForestRegressor()
model.fit(X_train_vec, y_train)

# Make predictions on the test data
predictions = model.predict(X_test_vec)

print(predictions)

[0.51296    0.23078    0.57343    0.50135    0.47211    0.48899
 0.41253    0.60688    0.37671    0.28113    0.53244    0.58918
 0.45853    0.56621    0.43964    0.35042    0.49586    0.44519
 0.48814    0.47057    0.58202    0.48171    0.47824    0.60216
 0.43106    0.56109    0.50567    0.52133    0.55319    0.544
 0.52937    0.57749    0.49702    0.47695    0.62784    0.5982
 0.48883    0.50862    0.60253    0.72478    0.76439    0.48963
 0.48738    0.5598     0.50621    0.52101    0.511205   0.41411
 0.73862    0.53081    0.45562    0.45888    0.42135    0.46566
 0.68466    0.39362    0.40519    0.53489    0.51494    0.44108
 0.44196    0.47442    0.48638    0.47049    0.47341    0.46695
 0.45675    0.44228    0.5077     0.41752    0.46613    0.40362
 0.5307     0.31372    0.42473    0.46656    0.48041    0.48301
 0.3908     0.51017    0.37134    0.39991    0.39725    0.52830667
 0.4293955  0.75439    0.51916    0.47077    0.45351    0.37129
 0.42995    0.52059    0.4715     0.60351    0.62225    0.61593
 0.61633    0.62731    0.43421    0.39715    0.38665    0.51507
 0.46625    0.67269    0.46229    0.52144    0.46335    0.46471
 0.47476    0.42288    0.39982    0.52913    0.74912    0.48661
 0.41946    0.42132    0.41728    0.40393    0.5105     0.47299
 0.45666    0.53187    0.50401    0.39223833 0.40774    0.37264
 0.5668     0.41656    0.44554    0.50545    0.62839    0.47458
 0.59077    0.46249    0.49209    0.442      0.51379    0.48304
 0.3856     0.46997    0.55087    0.57076    0.50518    0.47936
 0.72919    0.36375    0.48276    0.68418    0.45711    0.5391
 0.46637    0.55609    0.41946    0.52993    0.51714    0.54036
 0.59042    0.57073    0.46859    0.43107    0.51663    0.54175
 0.51665    0.51221    0.4884     0.44234    0.55456    0.35938
 0.41513    0.43688    0.47902    0.49006    0.36135    0.52115
 0.505158   0.40381    0.35256    0.66422    0.64691    0.47187
 0.42044    0.40314    0.58       0.48903    0.52562    0.46448
 0.68523    0.60377    0.42102    0.64495    0.63623    0.48099
 0.55852    0.31592    0.52212    0.57244    0.39946    0.58459
 0.59031    0.48302    0.50026    0.35782    0.492515   0.42592
 0.51436    0.50326    0.52804    0.5667     0.45587    0.37055
 0.46305    0.48212    0.55137    0.4563     0.57858    0.70081
 0.53145    0.66254    0.48822    0.48727    0.6194     0.44931
 0.55365    0.55736    0.47211    0.72104    0.6003     0.22973
 0.52807    0.43573    0.41651    0.49844    0.51316    0.57483
 0.47847    0.4628     0.39497    0.54725    0.43399    0.43395
 0.4506325  0.5589     0.68275    0.76031    0.44075    0.44036
 0.56217    0.56582    0.41674    0.47833    0.6103     0.50236
 0.48376    0.4452     0.53513    0.44161    0.56205    0.41985
 0.37996    0.51585    0.46291    0.46273    0.49278    0.49044
 0.51535    0.51426    0.40745    0.58426    0.55499    0.53238
 0.50854    0.59458    0.43725    0.61445    0.53267    0.43674
 0.4555125  0.52233    0.54168    0.42777    0.5396     0.39624
 0.42482    0.49535    0.38086    0.36729    0.65259    0.46258
 0.60225    0.41926    0.73718    0.46616    0.40966    0.51088
 0.45021    0.53009    0.44959    0.76542    0.48601    0.75423
 0.53759    0.53394    0.62343    0.35563    0.49397    0.45257
 0.41377    0.58232    0.45854    0.62197    0.5794     0.46503
 0.40579    0.40254667 0.39286    0.37743    0.56874    0.54425
 0.57277    0.42308    0.47802    0.45425    0.41992    0.56122
 0.54235    0.50009    0.5136     0.47622    0.49228    0.66265
 0.41979    0.50747    0.45731    0.65965    0.43392    0.43398
 0.54511    0.51787    0.46095    0.35195    0.39704    0.38677
 0.54075    0.42816    0.48881    0.45428    0.61895    0.44899
 0.46237    0.58532    0.52097    0.47147    0.38379    0.46967
 0.48193    0.43219667 0.42170667 0.44411    0.44162    0.51275
 0.71816    0.41595    0.53972    0.54862    0.55367    0.50802
 0.36486    0.53121    0.55063    0.61292    0.43935    0.45879
 0.48248    0.40914    0.44551    0.28835    0.51708    0.43216
 0.4488     0.54027    0.5503     0.45563    0.43715    0.45354
 0.30154    0.42547    0.50987    0.45594    0.63865    0.50069
 0.46252    0.40967    0.460665   0.56538    0.6356     0.54038
 0.492      0.50933    0.40558    0.4320925  0.42174    0.44946
 0.46799    0.50435    0.44531    0.20881    0.49735    0.44874
 0.44239    0.35879    0.65511    0.62954    0.41793    0.42218
 0.76104    0.75918    0.41097    0.62369    0.51943    0.67237
 0.35574    0.54931    0.5868     0.68924    0.45114    0.41229
 0.40039    0.61541    0.49435    0.3775     0.5945     0.48812
 0.4317     0.54067    0.52933    0.76789    0.50597    0.49276333
 0.77361    0.4473025  0.50553    0.47249    0.4917     0.53559
 0.51955    0.51934    0.51999    0.46774    0.47847    0.46577
 0.55394    0.55609    0.61547    0.45699    0.4909     0.50159
 0.47355    0.50285    0.52137    0.50272    0.55967    0.75628
 0.69387    0.51301    0.44359    0.41756    0.41385    0.45116
 0.52613    0.54226    0.3732     0.41886    0.47076    0.4482
 0.63111    0.49564    0.76447    0.53399    0.45219    0.48749
 0.75309    0.50211    0.55458    0.54814    0.52288    0.53908
 0.5071     0.36478    0.6838     0.47608    0.49066    0.4735
 0.29535    0.46068    0.42277    0.75107    0.744      0.51303
 0.76904    0.54495    0.74241    0.42309    0.37851    0.48026
 0.67237    0.47943    0.46809    0.50214    0.6576     0.4784
 0.63357    0.48002    0.443      0.59823    0.545      0.35034
 0.48377    0.63794    0.5033     0.52775    0.47113    0.39861
 0.48947    0.50201    0.53702    0.406755   0.32063    0.40608
 0.49489    0.5043     0.46284    0.60582    0.60917    0.43963
 0.43838    0.41147    0.68232    0.4426     0.53697    0.44616
 0.45402    0.44408    0.47788    0.45282    0.42275    0.41632
 0.49634    0.54234    0.40188    0.53475    0.45661    0.48239
 0.51351    0.47494    0.4691     0.54011    0.52272    0.78335
 0.78252    0.41556    0.43251    0.51833    0.60688    0.32134
 0.44223    0.43151    0.44875    0.58772    0.41517    0.41339
 0.73039    0.72804    0.39917    0.58066    0.46553333 0.52058
 0.42992    0.54094    0.51762    0.49564    0.27992    0.41574
 0.52577    0.48954    0.51497    0.65564    0.71789    0.4966
 0.39096    0.66688    0.48014    0.4154     0.42737    0.41422
 0.46211    0.45932    0.55886    0.51145    0.44661    0.51508
 0.40722    0.61254    0.49413    0.42505    0.5254     0.46823
 0.44461    0.62097    0.74044    0.58389    0.5107125  0.41588
 0.33354    0.67237    0.40144    0.60695    0.5334     0.67325
 0.58037    0.38593    0.48605    0.39403    0.45357    0.39182
 0.56315    0.52874    0.60011    0.53789    0.51716    0.7185
 0.51727    0.48908    0.46601    0.6456     0.65017    0.61078
 0.79418    0.36829    0.48509    0.4993     0.60612    0.49018
 0.44454    0.47533    0.3907     0.71233    0.55728    0.52064
 0.24252    0.5185     0.52945    0.37242    0.53322    0.53374
 0.4829     0.36148    0.42529    0.43368    0.43292    0.62758
 0.52406    0.68453    0.39694    0.43419    0.50018    0.47013
 0.55359    0.38199    0.46458    0.55297    0.55655    0.5188
 0.32768    0.56158    0.4635225  0.35873    0.46388    0.44715
 0.56958    0.45347    0.44554    0.62776    0.51473    0.47213
 0.52899    0.42698    0.57094    0.36754    0.49789    0.41096
 0.45588    0.577      0.75293    0.59732    0.37646    0.2549
 0.4551     0.23434    0.47294    0.60747    0.43826    0.41461
 0.38149    0.48856    0.47713    0.4684     0.39512    0.55466
 0.7613     0.52882    0.38341    0.48755    0.65662    0.60768
 0.49234    0.43105    0.74065    0.49562    0.4883     0.7663
 0.44375    0.54285    0.45949    0.66821    0.46347    0.44758
 0.31237    0.31178    0.43165    0.51498    0.54753    0.48389
 0.48741    0.58336    0.45171    0.42602    0.45688    0.44068
 0.43531    0.43907    0.37846    0.73219    0.7365     0.71398
 0.67613    0.71991    0.49181    0.52115    0.51641    0.42997
 0.51897    0.49331    0.47799667 0.48235667 0.42228    0.39982
 0.41464    0.21268    0.54083    0.51348   ]

In [24]:
# Fear Data
excel_file_path = 'Fear_Train.xlsx'
df4 = pd.read_excel(excel_file_path)

In [25]:
df4

                                       Combined_Coloumn
0     20000   I feel like I am drowning. #depression...
1     20001   I get so nervous even thinking about t...
2     20002   I lost my blinders .... #panic  fear  ...
3     20003   I feel like I am drowning. #depression...
4     20004   This is the scariest American Horror S...
...                                                 ...
1252  21252   Staff on @ryainair FR1005. Asked for i...
1253  21253   Staff on @ryainair FR1005. Asked for i...
1254  21254   An adviser to the #European #UnionÃ¢â‚¬â„¢s...
1255  21255   So about 18mths ago i signed up to @Lu...
1256  21256   So about 18mths ago i signed up to @Lu...

[1257 rows x 1 columns]

In [26]:
# Splitting the combined column into separate columns
df4[['Index', 'Comment', 'Emotion', 'Correlation']] = df4['Combined_Coloumn'].str.extract(r'^(\d+)\s+(.*?)\s+(\w+)\s+([\d.]+|None)$')

# Dropping the original combined column
df4.drop(columns=['Combined_Coloumn'], inplace=True)

In [36]:
df4

,Index,Comment,Emotion,Correlation
0,20000,I feel like I am drowning. #depression #anxiet...,fear,0.979
1,20001,I get so nervous even thinking about talking t...,fear,0.979
2,20002,I lost my blinders .... #panic,fear,0.975
3,20003,I feel like I am drowning. #depression #falur...,fear,0.938
4,20004,This is the scariest American Horror Story out...,fear,0.938
...,...,...,...,...
1252,21252,Staff on @ryainair FR1005. Asked for info and ...,fear,0.312
1253,21253,Staff on @ryainair FR1005. Asked for info and ...,fear,0.271
1254,21254,An adviser to the #European #UnionÃ¢â‚¬â„¢s top #co...,fear,0.500
1255,21255,So about 18mths ago i signed up to @Lumo_Energ...,fear,0.479
1256,21256,So about 18mths ago i signed up to @Lumo_Energ...,fear,0.271

In [115]:
df4 = df4.dropna()

In [123]:
df4

,Index,Comment,Emotion,Correlation,Fear_Intensity
0,20000,I feel like I am drowning. #depression #anxiet...,fear,0.979,0.0
1,20001,I get so nervous even thinking about talking t...,fear,0.979,0.0
2,20002,I lost my blinders .... #panic,fear,0.975,0.0
3,20003,I feel like I am drowning. #depression #falur...,fear,0.938,0.0
4,20004,This is the scariest American Horror Story out...,fear,0.938,0.0
...,...,...,...,...,...
1252,21252,Staff on @ryainair FR1005. Asked for info and ...,fear,0.312,0.0
1253,21253,Staff on @ryainair FR1005. Asked for info and ...,fear,0.271,0.0
1254,21254,An adviser to the #European #UnionÃ¢â‚¬â„¢s top #co...,fear,0.500,0.0
1255,21255,So about 18mths ago i signed up to @Lumo_Energ...,fear,0.479,0.0
1256,21256,So about 18mths ago i signed up to @Lumo_Energ...,fear,0.271,0.0

In [116]:
import pandas as pd

fear_keywords = {
    "terrifying": 1.0,
    "scared": 0.8,
    "afraid": 0.7,
    "fear": 0.9,
    "chills": 0.8
}

# Function to calculate fear intensity for a comment
def calculate_fear_intensity(comment):
    fear_score = 0
    # Ensure comment is a string before processing
    if isinstance(comment, str):
        # Iterate through fear-inducing keywords
        for keyword, weight in fear_keywords.items():
            # Count occurrences of keyword in the comment
            keyword_count = comment.lower().count(keyword)
            # Update fear score based on keyword count and weight
            fear_score += keyword_count * weight
    return fear_score

# Calculate fear intensity for each comment in the DataFrame
df4['Fear_Intensity'] = df4['Comment'].apply(calculate_fear_intensity)

C:\Users\DELL\AppData\Local\Temp\ipykernel_15316\414139422.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Fear_Intensity'] = df4['Comment'].apply(calculate_fear_intensity)

In [117]:
df4

,Index,Comment,Emotion,Correlation,Fear_Intensity
0,20000,I feel like I am drowning. #depression #anxiet...,fear,0.979,0.0
1,20001,I get so nervous even thinking about talking t...,fear,0.979,0.0
2,20002,I lost my blinders .... #panic,fear,0.975,0.0
3,20003,I feel like I am drowning. #depression #falur...,fear,0.938,0.0
4,20004,This is the scariest American Horror Story out...,fear,0.938,0.0
...,...,...,...,...,...
1252,21252,Staff on @ryainair FR1005. Asked for info and ...,fear,0.312,0.0
1253,21253,Staff on @ryainair FR1005. Asked for info and ...,fear,0.271,0.0
1254,21254,An adviser to the #European #UnionÃ¢â‚¬â„¢s top #co...,fear,0.500,0.0
1255,21255,So about 18mths ago i signed up to @Lumo_Energ...,fear,0.479,0.0
1256,21256,So about 18mths ago i signed up to @Lumo_Energ...,fear,0.271,0.0

In [118]:
file_path = 'fear_intensity.xlsx'

# Save the DataFrame as an Excel file
df.to_excel(file_path, index=False)

In [119]:
excel_file_path = 'Fear_Test.xlsx'

In [120]:
df5 = pd.read_excel(excel_file_path)

In [121]:
df5

                                      Combined_Coloumn
0    21257   #Matthew 25; 1-13\nCould somebody shoo...
1    21258   @bkero @whispersystems Which really su...
2    21259   Be #afraid of the #quiet ones they are...
3    21260   @riinkanei he's a horrible person and ...
4    21261   What we fear doing most is usually wha...
..                                                 ...
990  22247   @01Starblazer 9 -9 vs Atlanta this yr,...
991       22248   I'm shaking now.        fear    NONE
992  22249   me: are you guys dating yet #trans #ne...
993  22250   She: Why are you listening to The Eury...
994  22251   and claimed that all of the same thing...

[995 rows x 1 columns]

In [62]:
pattern = r'(\d+)\s+(.+?)\s+(\w+)\s+(NONE)'

# Apply the pattern using str.extract method to extract values into separate columns
df6 = df5['Combined_Coloumn'].str.extract(pattern, expand=True)

# Rename columns
df6.columns = ['Index', 'Comment', 'Emotion', 'Correlation']

In [63]:
df6

,Index,Comment,Emotion,Correlation
0,21257,#Matthew 25; 1-13\nCould somebody shoot a #vid...,fear,NONE
1,21258,@bkero @whispersystems Which really sucks beca...,fear,NONE
2,21259,Be #afraid of the #quiet ones they are the one...,fear,NONE
3,21260,@riinkanei he's a horrible person and now i ga...,fear,NONE
4,21261,What we fear doing most is usually what we mos...,fear,NONE
...,...,...,...,...
990,22247,"@01Starblazer 9 -9 vs Atlanta this yr, 2 - 11 ...",fear,NONE
991,22248,I'm shaking now.,fear,NONE
992,22249,me: are you guys dating yet #trans #nervous #b...,fear,NONE
993,22250,She: Why are you listening to The Eurythmics?\...,fear,NONE
994,22251,and claimed that all of the same things could ...,fear,NONE

In [126]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# Load training and test data
train_data = df4
test_data = df6

# Define X_train and y_train
X_train = train_data['Comment']
y_train = train_data['Correlation']

# Define X_test
X_test = test_data['Comment']

# Vectorize comments using TF-IDF
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train Random Forest Regressor model
model = RandomForestRegressor()
model.fit(X_train_vec, y_train)

# Make predictions on the test data
predictions = model.predict(X_test_vec)

print(predictions)

[0.42119    0.43245    0.43483    0.51596    0.40181    0.40642
 0.82131    0.39406    0.41694    0.52681    0.73316    0.51164
 0.50389    0.4491     0.43421    0.54787    0.40146    0.63643
 0.42       0.40632    0.5024     0.40864    0.42687    0.47853
 0.45337    0.73197    0.50944    0.50525    0.4741     0.47502
 0.39249    0.6631     0.43343    0.59001    0.66389    0.43491
 0.44501    0.78004    0.47317    0.47772    0.50136    0.46084
 0.45332    0.46912    0.61055    0.45832    0.43819    0.5074
 0.46077    0.57444    0.58777    0.54775    0.45112    0.83861
 0.41183    0.8018     0.43557    0.47536    0.38871    0.68271
 0.36229    0.42346    0.45274    0.54125    0.77648    0.4633
 0.43481    0.5274     0.63062    0.48828    0.46057    0.43456
 0.59134    0.6571     0.85095    0.46807    0.46085    0.45948
 0.45629    0.53091    0.32493    0.5156     0.85356    0.47225
 0.37247    0.59607    0.39004    0.4062     0.37757    0.46194
 0.5046     0.39724    0.45215    0.37704    0.45676    0.36991
 0.44353    0.633405   0.4987     0.49359    0.33477    0.51739
 0.51739    0.49228    0.48997    0.83106    0.48457    0.3253
 0.47501    0.49463    0.57272833 0.57583    0.581805   0.41092
 0.64983    0.62029    0.61879    0.45521    0.4696     0.36283
 0.45518    0.47905    0.46043    0.46132    0.42588    0.45652
 0.47725    0.67303    0.60806    0.50591    0.546705   0.44566
 0.38282    0.44389    0.44292    0.54338    0.74291    0.44595
 0.46961    0.51494    0.33912    0.43476    0.46809    0.51339
 0.65645    0.49962    0.65706    0.64392    0.62947    0.59685
 0.79916    0.43263    0.40742    0.40778    0.66008    0.66152
 0.33723    0.66212    0.4977     0.48254    0.1588     0.44146
 0.44115    0.52874    0.428      0.49321    0.38331    0.35571
 0.64586    0.44705    0.62647    0.35747    0.40248    0.64622
 0.80287    0.43217    0.47137    0.71364    0.38204    0.36648
 0.37866    0.73322    0.59875917 0.44222    0.44061    0.43523
 0.6627     0.30204    0.46988    0.39882    0.50774    0.51371
 0.4781     0.45766    0.82278    0.51978    0.49612    0.49994
 0.41889    0.64365    0.39713    0.75341    0.46739    0.41465
 0.49298    0.28626    0.58844    0.69605    0.44908    0.60039
 0.82358    0.43415    0.47627    0.48387    0.4153     0.40716
 0.68903    0.51206    0.65126    0.65064    0.81849    0.34382
 0.70523    0.46245    0.46509    0.18004    0.39426    0.45435
 0.442      0.77282    0.65353    0.47373    0.48455    0.4906
 0.43865    0.45473    0.46618    0.33561    0.65277    0.43462
 0.52728    0.40587    0.40169    0.59771    0.65854    0.45136
 0.40833    0.47403    0.47619    0.41517    0.5784     0.42373
 0.45737    0.6403     0.59692    0.4838     0.69536    0.52556
 0.57012    0.45514    0.36705    0.78604    0.37173    0.42141
 0.71249    0.5691     0.26159    0.529      0.4511     0.35941
 0.41117    0.68311    0.39447    0.50607    0.49225    0.85404
 0.35431    0.38317    0.714      0.49923    0.37595    0.36566
 0.44557    0.48986    0.47401    0.80385    0.45427    0.44024
 0.46758    0.57855    0.77313    0.77974    0.1514     0.66467
 0.42928    0.45581    0.64867    0.70851    0.81041    0.42595
 0.65419    0.47652    0.63012    0.47694    0.35939    0.5047
 0.48519    0.48829    0.42988    0.4247     0.49268    0.44262
 0.564055   0.47477    0.43324    0.42033    0.45247    0.60177
 0.43575    0.49546    0.45175    0.79829    0.50284    0.48646
 0.63187    0.38162    0.56657    0.47475    0.78195    0.85532
 0.6747     0.50952    0.51174    0.52498    0.72245    0.33469
 0.51584    0.48772    0.47299    0.40612    0.64099    0.62934
 0.4653     0.51841    0.73936    0.3879     0.43225    0.4456
 0.41324    0.58004    0.57756    0.53474    0.32559    0.43415
 0.4969     0.82409    0.4668     0.54817    0.48445    0.48436
 0.46525    0.45076    0.65725    0.46848    0.45677    0.44443
 0.42798    0.44632    0.43895    0.32074    0.45546    0.44417
 0.74529333 0.686      0.47082    0.81204    0.75577    0.42746
 0.383      0.46329    0.46308    0.56314    0.39012    0.36236
 0.41966    0.50638    0.41326    0.39278    0.60455    0.47115
 0.39448    0.53023    0.39151    0.64446    0.44747    0.53726
 0.53197    0.59094    0.48057    0.45485    0.86523    0.86417
 0.45406    0.46331    0.86573    0.38703    0.48525    0.63994
 0.50705    0.46201    0.68601    0.40518    0.42322    0.41948
 0.45146    0.42563    0.46491    0.44229    0.46868    0.60131
 0.40299    0.7762     0.66312    0.45758    0.41649    0.58871
 0.42865    0.37665    0.30807    0.6589     0.65138    0.72213
 0.65962    0.34713    0.51223    0.607575   0.80481    0.38544
 0.23608    0.44445    0.43244    0.44525    0.44655    0.41711
 0.42786    0.57096    0.58835    0.63991    0.7005     0.38699
 0.44371    0.68994    0.69032    0.81639    0.39724    0.36209
 0.37016    0.48174    0.4897     0.46975    0.46656    0.63983
 0.50583    0.51093    0.43838    0.49255    0.47856    0.43413
 0.7439     0.42767    0.40825    0.52752    0.55212    0.71395
 0.4942     0.4668     0.38341    0.41201    0.30345    0.74559
 0.68485    0.47605    0.38141    0.64604    0.47137    0.44852
 0.39       0.39981    0.46969    0.45242    0.66581    0.70154
 0.34288    0.62412    0.46302    0.40897    0.40699    0.34518
 0.637375   0.46629    0.43969    0.47597    0.53526    0.47165
 0.47631    0.47616    0.82562    0.38653    0.4578     0.32538
 0.40448    0.41177    0.43883    0.487      0.43679    0.59591
 0.45136    0.42336    0.32545    0.50022    0.42256    0.41414
 0.38752    0.46202    0.54345    0.48144    0.4889     0.58973
 0.4235     0.48446    0.40052    0.44942    0.38651    0.67437
 0.47341    0.46413    0.48683    0.43528    0.33327    0.63773
 0.31143    0.14519    0.66782    0.46955    0.47064    0.4634
 0.39663    0.35322    0.53708    0.49404    0.37217    0.3997
 0.39161    0.42121    0.46952    0.33946    0.52883    0.43001
 0.71533    0.53226    0.50326    0.49197    0.49689    0.50959
 0.5072     0.34951    0.67991    0.35371    0.42338    0.38281
 0.36566    0.40344    0.47575    0.45496    0.48179    0.44296
 0.55992    0.77232    0.40698    0.41918    0.62468    0.39149
 0.82038    0.40873    0.44122    0.53084    0.48022    0.4633
 0.44582    0.36866    0.46883    0.51607    0.81642    0.39686
 0.48117    0.73748    0.51521    0.5855     0.52337    0.5247
 0.81903    0.43009    0.43952    0.60255    0.51152    0.68613
 0.38808    0.66813    0.64681    0.15269    0.41875    0.4167
 0.50894    0.519      0.3696     0.46733    0.39075    0.44085
 0.42499    0.46402    0.72513    0.49409    0.81518    0.47049
 0.40305    0.55208    0.49721    0.5761     0.49559    0.73456
 0.49755    0.46607    0.46479    0.48569    0.51716    0.31038
 0.50551    0.47007    0.62453    0.79614    0.38626    0.52765
 0.32613    0.50059    0.44597    0.68052    0.42037    0.36667
 0.29429    0.43345    0.46694    0.49605    0.45018    0.38703
 0.38703    0.36719    0.37169    0.45275    0.42657    0.78024
 0.46713    0.52392    0.82909    0.41289    0.39285    0.4398
 0.46516    0.65414    0.45098    0.53079    0.45997    0.34478
 0.49072    0.46013    0.33147    0.45642    0.4287     0.66488
 0.66318    0.40529    0.36686    0.46136    0.43106    0.39269
 0.49896    0.39985    0.64198    0.67482    0.67364    0.48754
 0.80519    0.40638    0.42661    0.48422    0.48351    0.38619
 0.38703    0.39131    0.38104    0.40027    0.67663    0.51245
 0.43927    0.4853     0.47273    0.4178     0.48667    0.46368
 0.43174    0.48952    0.44176    0.42778    0.72357    0.42836
 0.42606    0.49084    0.41517    0.42654    0.42654    0.441
 0.19084    0.4046     0.47223    0.62239    0.38322    0.82988
 0.57556    0.38876    0.43345    0.60113    0.59947    0.685
 0.5374     0.46659    0.72483    0.43289    0.47196    0.62498
 0.40344    0.51448    0.56471    0.58342    0.49763    0.38703
 0.38703    0.55219    0.7895     0.2149     0.71418    0.60966
 0.60347    0.82392    0.40586    0.54505    0.64771    0.37786
 0.47016    0.63259    0.43437    0.43753    0.57875    0.85252
 0.37902    0.13469    0.53773    0.4821     0.45745    0.30828
 0.3492     0.84024    0.52567    0.43336    0.48659    0.64165
 0.73481    0.79261    0.37961    0.36412    0.37786    0.61459
 0.40436    0.40705    0.4078     0.44702    0.49676    0.63865
 0.47957    0.52176    0.42173    0.48009    0.46328    0.68762
 0.4928     0.4759     0.48335    0.4171     0.48439    0.65417
 0.51871    0.46088    0.74356    0.40628    0.81563    0.4761
 0.68311    0.5451     0.74495    0.4725     0.80151    0.49856
 0.46513    0.5082     0.52662    0.68533    0.47272    0.46383
 0.82063    0.50359    0.80927    0.71185    0.39993    0.62989
 0.66369    0.49286    0.16426    0.7633     0.42999    0.47292
 0.41634    0.39916    0.62969    0.69826    0.35543    0.34853
 0.55374    0.12927    0.45043    0.38727    0.48403    0.62468
 0.44518    0.4657     0.4963     0.62986488 0.6754     0.42526
 0.40176    0.35279    0.47532    0.35747    0.77636    0.49609
 0.37213    0.52524    0.5369     0.45498    0.40336    0.48496
 0.67826    0.81081    0.41221    0.53419    0.45502    0.46421
 0.40741    0.41232    0.46868    0.46101    0.49172    0.42232
 0.43192    0.75168    0.48093    0.43637    0.403      0.77774
 0.40517    0.51622    0.55408    0.394      0.46878    0.38276
 0.71511    0.43599    0.45781    0.37996    0.77957    0.78195
 0.4695     0.26118    0.41678    0.58764    0.67562    0.43434
 0.38816    0.66358    0.4609     0.57896    0.47334    0.4653
 0.51384    0.45313    0.50505    0.5838     0.77472    0.46883
 0.56344    0.47826    0.70315    0.4285     0.55823    0.59595
 0.4605     0.16632    0.78431    0.38703    0.54789    0.38821
 0.31276    0.66175    0.55421    0.52408    0.44117    0.41261
 0.48413    0.45483    0.39645    0.40016    0.52425    0.69137
 0.40396    0.46568    0.8119     0.48125    0.42032    0.6521
 0.41549    0.38562    0.39638    0.39491    0.34656    0.68756
 0.42       0.40917    0.40553    0.53221    0.75043    0.7728
 0.3745     0.269      0.623085   0.41744    0.5645     0.45722
 0.62469    0.65964    0.45515    0.41495    0.50902    0.4969
 0.70039    0.6946     0.42888    0.59154    0.48914    0.57581
 0.44602    0.65224    0.63579    0.38972    0.69685    0.20083
 0.40226    0.43801    0.63061    0.50262    0.54248    0.40005
 0.35008    0.22672    0.53861    0.43968    0.38716    0.66427
 0.78111    0.33389    0.83392    0.45299    0.41885    0.73228
 0.73249    0.42682    0.78063    0.4207     0.47135   ]